version: '3.8'

services:

  sql-db:
    image: postgres:15.2
    container_name: great_travel
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=great_travel
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  cache-db:
   image: redis:6.2-alpine
   container_name: great_travel_cache
   restart: always
   ports:
    - "6379:6379"
   command: redis-server --loglevel warning --requirepass great
